[project]
name = "pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sudarsan", email = "sudarsan.katam@tuhh.de" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "tensorboard>=2.21.0",
    "torch[device-gfx1151]==2.13.0+rocm10.0.0",
    "torchaudio==2.11.0.2+rocm10.0.0",
    "torchinfo>=1.8.0",
    "torchmetrics>=1.9.0",
    "torchvision[device-gfx1151]==0.28.0+rocm10.0.0",
    "tqdm>=4.70.0",
]

[project.scripts]
pytorch = "pytorch:main"

[[tool.uv.index]]
url = "https://stable.repo.amd.com/rocm/whl-next/"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
